### ISSUE TITLE
USER STORY: Navigation Bar

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/you-made-you-fitness#1]
Epic: Navigation

As a **site user**, I can **easily find the navigation bar**, so that **I can navigate the different pages of the site**. 

**Acceptance Criteria:**
- [x] The navigation bar is located and visible at the top of the screen at all times.
- [x] The navbar items are presented horizontally on desktop and collapse into a hamburger menu on smaller screens. 
- [x] The navbar items have relevant names/icons in relation to their links.
- [x] The nav items are different for unregistered and registered users.

**Tasks:**
- [x] Create a responsive navigation bar with Bootstrap.
- [x] Link each nav item to its relevant page on the site. 
- [x] Add font awesome icons. 
- [x] Add if statements in code to ensure that unregistered users cannot access content for registered users.
