### ISSUE TITLE
USER STORY: Web Shop

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/you-made-you-fitness#10]
Epic: Content

As a site user, I can open the web shop, so that I can scroll through the products the fitness community offers.

**Acceptance Criteria:**
- [x] The web shop is displayed on its own page.
- [x] The products are clearly displayed through categories and images. 
- [x] The web shop has a clean design that matches the rest of the site. 

**Tasks:**
- [x] Create a Django app for the web shop with templates, views, models, and urls.
- [x] Add customized styling using CSS. 
- [x] Complete user stories for the epic "Web Shop".
