### ISSUE TITLE
USER STORY: Blog Page

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/you-made-you-fitness#11]
Epic: Content

As a registered user, I can view the blog page, so that I can take part of other member's posts.

**Acceptance Criteria:**
- [x] The blog page is displayed on its own page for registered user's only.
- [x] The blog page has a clean design that matches the rest of the site. 

**Tasks:**
- [x] Create a Django app for the blog page with templates, views, models, forms, and urls. 
- [x] Install summernote. 
- [x] Add customized styling using CSS. 
- [x] Complete user stories for the epic "Blog Post".
