### ISSUE TITLE
USER STORY: Reset Password

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/you-made-you-fitness#12]
Epic: Registration and Account Management

As a registered user, I can reset my password, so that I can access my information and keep my account safe. 

**Acceptance Criteria:**
- [ ] The user can select "forgot password" on the login page to reset their password using email. (MAY NOT BE IMPLEMENTED THIS RELEASE). 
- [ ] The user can change their password on their profile page when already logged in.

**Tasks:**
- [ ] Add functionality to reset password (allauth?). Research how to implement this.
