### ISSUE TITLE
USER STORY: Update Profile

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/you-made-you-fitness#13]
Epic: Registration and Account Management

As a registered user, I can change my profile information, so that I can ensure it is up to date. 

**Acceptance Criteria:**
- [ ] The user can make changes to their profile page when already logged in.

**Tasks:**
- [ ] Create button for updating profile.
- [ ] Add view and functionality to edit profile form.
