### ISSUE TITLE
USER STORY: Delete Account

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/you-made-you-fitness#14]
Epic: Registration and Account Management

As a registered user, I can delete my account, so that I have the option to remove my information from the site. 

**Acceptance Criteria:**
- [ ] The user can delete their account by clicking a button.
- [ ] An alert is displayed asking the user if they are sure they want to delete their account.

**Tasks:**
- [ ] Add functionality to delete account (allauth?). Research how to implement this.
