### ISSUE TITLE
USER STORY: View Products

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/you-made-you-fitness#15]
Epic: Web Shop

As a site user, I can view the products in the web shop, so that I can decide if I want to make a purchase.

**Acceptance Criteria:**
- [x] The products are evenly displayed on the page no matter the screen size they are being viewed on.
- [x] The user can click on a product to get to the product page with more information. 
- [x] Each product is accompanied by an image and description.

**Tasks:**
- [x] Add columns for different screen sizes using Bootstrap. 
- [x] Create a product detail page. 
- [x] Import images and add descriptions for each product. 
- [x] Add functionality to add product to shopping bag.
