### ISSUE TITLE
USER STORY: Search for Products

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/you-made-you-fitness#16]
Epic: Web Shop

As a site user, I can search for products by category or name, so that I can find what I am looking for.

**Acceptance Criteria:**
- [ ] The search bar is clearly visible in the web shop.
- [ ] The products are sorted by category. 
- [ ] An error message is displayed if there are no search results.

**Tasks:**
- [ ] Add a search bar in the product template (using Bootstrap?). 
- [ ] Research how to implement search bar functionality. 
- [ ] Create pages for each category. 
- [ ] Create page to display when there are no search results.
