### ISSUE TITLE
USER STORY: Add to Shopping Bag

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/you-made-you-fitness#17]
Epic: Web Shop

As a site user, I can add products to my shopping bag, so that I can prepare for making a purchase.

**Acceptance Criteria:**
- [x] The user can add in a product from the product detail view.
- [x] The shopping cart amount is updated when items are added/deleted.
- [x] A message is displayed if a product has been added to the shopping bag successfully.

**Tasks:**
- [x] Implement functionality to add a product.
- [x] Create a shopping cart app and functionality.
- [x] Import Django messages and add a success message in the views (with the help of bootstrap alerts?).
