### ISSUE TITLE
USER STORY: Edit Shopping Bag

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/you-made-you-fitness#18]
Epic: Web Shop

As a site user, I can delete the products in my shopping bag, so that I can easily make changes if needed.

**Acceptance Criteria:**
- [x] The user can delete a product from the shopping bag.

**Tasks:**
- [x] Add "delete" button/icon and functionality. 
- [x] Watch CI walkthrough "Boutique Ado" to refresh knowledge about implementing this functionality.
