### ISSUE TITLE
USER STORY: Checkout

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/you-made-you-fitness#19]
Epic: Web Shop

As a registered user, I can fill out my contact and payment information, so that I can complete the purchase.

**Acceptance Criteria:**
- [x] There is a form to fill out asking for contact and payment information.
- [ ] There is an option (checkbox) to save the information for future purchases (won't have). 
- [x] The user is relocated to a "thank you" page when the purchase is completed successfully. 

**Tasks:**
- [x] Use stripe to implement checkout functionality.
- [ ] Implement functionality to save information to the logged in user (won't have).
- [x] Create a "thank you" page and relocate to this in the view if purchase was successful.
