### ISSUE TITLE
USER STORY: Business Logo

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/you-made-you-fitness#2]
Epic: Navigation

As a **site user**, I can **relocate to the home page by clicking the business logo in the navbar**, so that **it is easily accessible when needed**. 

**Acceptance Criteria:**
- [x] The business logo is clearly displayed in the navigation bar.
- [x] Hovering over the logo changes the mouse to a hand/finger to indicate that it is clickable. 
- [x] The logo is linking to the home page. 

**Tasks:**
- [x] Design the business logo to fit the rest of the site.
- [x] Include the logo when creating the navigation bar with Bootstrap. 
- [x] Link the logo to the home page in base HTML file.
