### ISSUE TITLE
USER STORY: Make Blog Post

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/you-made-you-fitness#20]
Epic: Blog Posts

As a registered user, I can make a blog post, so that I can share content with the community. 

**Acceptance Criteria:**
- [x] The user can add a title and text content to a blog post form. 
- [ ] The user can add an image (optional) (won't have, to be fixed in a future release).
- [x] The "posted by" author is the same as the logged in user. 

**Tasks:**
- [x] Add form with a field for title, a textbox (summernote), and an optional field to include an image.
- [ ] Add functionality to upload an image for users. (won't have, to be fixed in a future release).
- [x] Create button to submit form. 
- [x] Set "posted by" to logged in user in HTML template.
