### ISSUE TITLE
USER STORY: Edit/Delete Blog Post

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/you-made-you-fitness#21]
Epic: Blog Posts

As a registered user, I can edit or delete my blog post, so that it is possible to make changes if needed. 

**Acceptance Criteria:**
- [x] The user can edit their blog post after it has been posted. 
- [x] The user can delete their blog posts. 
- [x] The option to edit/delete is only displayed for the blog posts posted by the logged in user. 
- [x] The user gets a confirmation when changes has been made.

**Tasks:**
- [x] Add functionality to edit posts in views.py for the blog app. 
- [x] Add functionality to delete posts in views.py for the blog app. 
- [x] Include {% empty %} in HTML code for when there is nothing to show. 
- [x] Include success messages that are displayed to the user (make sure Django messages is imported).
