### ISSUE TITLE
USER STORY: Like Blog Posts

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/you-made-you-fitness#22]
Epic: Blog Posts

As a registered user, I can like or unlike other user's vlog posts, so that I can interact with their content.

**Acceptance Criteria:**
- [ ] Users can click a heart on other users blog posts to like it. 
- [ ] The heart is filled out when the post is liked. 
- [ ] The number of likes is displayed next to the heart. 

**Tasks:**
- [ ] Add heart font awesome icon and add customized CSS styling.
- [ ] Make icon clickable and count likes using JavaScript (in combination with HTML to display number of likes with each post).
