### ISSUE TITLE
USER STORY: Add Products

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/you-made-you-fitness#23]
Epic: Admin

As a site admin, I can manage (add, edit, delete) products in the web shop, so that I can ensure it is up to date.

**Acceptance Criteria:**
- [x] The site admin can add, edit, and delete products through the admin panel. 

**Tasks:**
- [x] Create Django superuser. 
- [x]  Add functionality for admins to add, edit and delete products in the web shop.
