### ISSUE TITLE
USER STORY: Manage Blog Posts

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/you-made-you-fitness#24]
Epic: Admin

As a site admin, I can delete blog posts made by users, so that I can ensure that available content is appropriate and following community guidelines. 

**Acceptance Criteria:**
- [x] The site admin can delete blog posts through the admin panel.

**Tasks:**
- [x] Make sure Django superuser is created.
- [x] Add functionality for admins to delete blog posts.
