### ISSUE TITLE
USER STORY: Search for Blog Posts

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/you-made-you-fitness#26]
Epic: Blog Posts

As a registered user, I can search for blog posts using key words, so that I can find specific content.

**Acceptance Criteria:**
- [x] The search bar is clearly visible on the community post page.
- [x] The search results are displayed as post titles that if clicked display the post detail page.

**Tasks:**
- [x] Add a search bar in community template (using Bootstrap?). 
- [x] Research how to implement search bar functionality. 
- [x] Create page to display for search results (and for when there are no results).
