### ISSUE TITLE
USER STORY: Home Page

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/you-made-you-fitness#3]
Epic: Content

As a **site user**, I can **understand the purpose of the site simply by looking at the home page**, so that **I can decide if I want to explore the content further**. 

**Acceptance Criteria:**
- [x] The home page contains hero image with hero text on the theme of the business.
- [x] The home page is divided into sections that link to the most important and popular content of the site.
- [x] The design is clean and not distracting from the content.

**Tasks:**
- [x] Add a hero image with relevant text to landing page.
- [x] Add sections using Bootstrap columns and link to other parts of the site. 
- [x] Create a clean design using HTML and CSS (including Bootstrap).
