### ISSUE TITLE
USER STORY: Social Media Links

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/you-made-you-fitness#4]
Epic: Content

As a **site user** I can **find the fitness community's social media links** so that **I can learn more about their buisness**. 

**Acceptance Criteria:**
- [x] The social media links are placed in the footer. 
- [x] The social media links are Instagram, Facebook, and YouTube. 
- [x] The links are represented by relevant font awesome icons.

**Tasks:**
- [x] Include links to social media when creating the footer using bootstrap.
- [x] Import relevant font awesome icons and style using CSS. 
- [x] Add hovering effect using CSS.
