### ISSUE TITLE
USER STORY: Create Account

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/you-made-you-fitness#5]
Epic: Registration and Account Management

As an **unregistered user** I can **create an account** so that **I can make purchases and take part of blog posts**. 

**Acceptance Criteria:**
- [x] The signup page is linked on the home page and in the navigation bar for unregistered users.
- [x] The design of the signup page matches the rest of the site.
- [x]  The user has to pick a username and password to create an account. Email is optional. 

**Tasks:**
- [x] Include link to signup page when creating bootstrap navbar.
- [x] Add linked button to signup page on home page. 
- [x] Create form to register using allauth. 
- [x] Modify the design using CSS so it fits the rest of the site. 
- [x] Make sure the form cannot be submitted without a username and password.
