### ISSUE TITLE
USER STORY: Login

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/you-made-you-fitness#6]
Epic: Registration and Account Management

As a **registered user** I can **easily login to my account** so that **I can access my profile and the content for registered users**. 

**Acceptance Criteria:**
- [x] The login page is linked in the navigation bar for unregistered users.
- [x] The user can login with their username and password.
- [x] The design of the login page matches the rest of the site.

**Tasks:**
- [x] Include login page when creating bootstrap navbar. 
- [x] Create login functionality using allauth. 
- [x] Modify the design using CSS so that it fits the rest of the site. 
- [x] Make sure both username and password are required to login.
