### ISSUE TITLE
USER STORY: Logout

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/you-made-you-fitness#7]
Epic: Registration and Account Management

As a **registered user** I can **easily logout from my account** so that **I can protect my personal information**. 

**Acceptance Criteria:**
- [x] The logout page is linked in the navigation bar for registered users.
- [x] The user is logged out by clicking "logout" on the logout page (linked in the navbar). 

**Tasks:**
- [x] Include link to logout page when creating bootstrap navbar (after an if statement checking for authenticated users). 
- [x] Create logout functionality using allauth. 
- [x] Modify the design using CSS so that it fits the rest of the site.
