### ISSUE TITLE
USER STORY: Contact Information

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/you-made-you-fitness#8]
Epic: Content

As a site user, I can find the business contact information, so that I know how to get in touch with them.

**Acceptance Criteria:**
- [x] The contact information is displayed on its own page and linked in the navigation bar.
- [x] The contact information includes an email address. No map or address needed as it is an online business.
- [x] Add newsletter signup.

**Tasks:**
- [x] Create a contact.html file.
- [x] Structure the information using Bootstrap.
- [x] Add contact to the navigation bar and link the relevant file.
- [x] Implement newletter signup functionality using Mailchimp.
