### ISSUE TITLE
USER STORY: About Us Section

### ISSUE THREAD

**Issue by gustafsson96** [gustafsson96/you-made-you-fitness#9]
Epic: Content

As a site user, I can find a section with information about the fitness community, so that I can learn more about it.

**Acceptance Criteria:**
- [x] The "about us" section is displayed on the home page and contains an informative text.
- [x] The design is clean and simple so it does not distract from the text.

**Tasks:**
- [x] Add an "about us" section to the home page.
- [x] Style a clean and simple design using CSS.
